# _config.yml
title: vcapy
description: goods not found elsewhere
contact_email: contact@vcapy.com
instagram_handle: "@vcapy"

collections:
  products:
    output: true
    permalink: /shop/products/:name/
  productlines:
    output: true
    permalink: /shop/productlines/:name/
